---
title: "Computing prior probabilities"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Computing prior hyperparameters

### <i><b><span style="color:salmon">---Special considerations: this portion is highly parallelizable---</span></b></i>

We are now just about ready to set up our MCMC. First, we need to determine the hyperparameters in the priors of our Gaussian mixture. These are all calculated in an empirical Bayesian manner -- that is, we can recycle information from the pairwise fits to inform our priors in the full-information mixture. This task can be split into 2 sub-tasks:

1. computing the prior hyperparameters for the cluster mixing weights

2. computing every other hyperparameter

The former is the most essential, as it helps us remove more candidate latent classes, ensuring that the number of clusters is fewer than the number of observations. **An important note**: this is the *only* step of LIEB that requires some sort of human intervention, but it does need to happen. A threshold, called $\delta$ in the manuscript, determines how strict one is about including classes in the final model. $\delta\in\{0,1,\ldots,\hat{M}\}$, where $\hat{M}$ is the number of candidate latent classes determined by the `get_reduced_classes()` function, as calculated in the previous step.

To get the prior weights on each candidate latent class, use the function `get_prior_weights()`. This function defaults to the settings used in the LIEB manuscript. The user can specify:

1. `reduced_classes`: the matrix of candidate latent classes generated by `get_reduced_classes()`

2. `fits`: the list of pairwise fits generated by `get_pairwise_fits()`

3. `parallel`: logical specifying if the analysis should be run in parallel (defaults to FALSE)

4. `ncores`: if in parallel, how many cores to use. Defaults to 20.

5. `delta`: this is the range of thresholds to try, but it will defaults to a sequence of all possible thresholds.

**NB:** while parallelization is always available here, it is not always necessary. Speed of this portion depends on sample size, dimension, and the number of candidate latent classes (in `reduced_classes`). 

Now, we are ready to compute the prior weights.
```{r, message = FALSE, echo = 3:11}
library(LIEB)

# Read in the candidate latent classes produced in the last step
reduced_classes <- readr::read_tsv("output/red_class.txt", col_names = FALSE)

# load in the pairwise fits from the first step
# (in this example case, I am simply loading the data from the package)
data("fits")

# Compute the prior weights
prior_weights <- get_prior_weights(reduced_classes, fits, parallel = FALSE)
```

